services:
  database:
    image: postgres:15-alpine
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pedidos:
    build: ./services/pedidos
    env_file: .env
    # Porta 3000 interna (acessível apenas via Gateway ou outros serviços)
    depends_on:
      database:
        condition: service_healthy

  estoque:
    build: ./services/estoque
    environment:
      - PORT=3001

  pagamentos:
    build: ./services/pagamentos
    environment:
      - PORT=3002

  api-gateway:
    build: ./services/api-gateway
    ports:
      - "8080:8080" # Porta principal de entrada para o usuário
    depends_on:
      - pedidos
      - estoque
      - pagamentos

volumes:
  postgres_data: